# Generated by Django 4.2.2 on 2023-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images', verbose_name='Site Logo')),
                ('page1', models.CharField(max_length=30, verbose_name='Page1')),
                ('page2', models.CharField(max_length=30, verbose_name='Page2')),
                ('page3', models.CharField(max_length=30, verbose_name='Page3')),
                ('page4', models.CharField(max_length=30, verbose_name='Page4')),
            ],
        ),
    ]
