# Generated by Django 4.2.2 on 2023-06-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=60, verbose_name='name1')),
                ('name2', models.CharField(max_length=60, verbose_name='name2')),
                ('text', models.TextField(verbose_name='Text')),
                ('button_name', models.CharField(max_length=60, verbose_name='Button Name')),
                ('img', models.ImageField(upload_to='images', verbose_name='image')),
                ('price', models.CharField(max_length=60, verbose_name='Price')),
                ('offer', models.CharField(max_length=60, verbose_name='Offer')),
            ],
        ),
    ]
