# Generated by Django 4.2.2 on 2023-06-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='image')),
                ('price1', models.CharField(max_length=60, verbose_name='Price1')),
                ('price2', models.CharField(max_length=60, verbose_name='Price2')),
                ('category', models.CharField(max_length=30, verbose_name='Category ')),
                ('name', models.CharField(max_length=30, verbose_name=' name')),
            ],
        ),
    ]
