# Generated by Django 4.2.2 on 2023-06-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_trending_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=60, verbose_name='name1')),
                ('name2', models.CharField(max_length=60, verbose_name='name2')),
                ('button_name', models.CharField(max_length=60, verbose_name='Button Name')),
            ],
        ),
    ]
