# Generated by Django 4.2.2 on 2023-06-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=60, verbose_name='name1')),
                ('name2', models.CharField(max_length=60, verbose_name='name2')),
                ('name3_blue', models.CharField(max_length=60, verbose_name='name3 Blue')),
                ('name4', models.CharField(max_length=60, verbose_name='name4')),
                ('text', models.TextField(verbose_name='Text')),
                ('button_name', models.CharField(max_length=60, verbose_name='Button Name')),
            ],
        ),
    ]
