# Generated by Django 4.2.2 on 2023-06-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_product_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='imge')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('price1', models.CharField(max_length=60, verbose_name='Price1')),
                ('price2', models.CharField(max_length=60, verbose_name='Price2')),
                ('text', models.TextField(verbose_name='Text')),
                ('button_name', models.CharField(max_length=60, verbose_name='Button Name')),
                ('category1', models.CharField(max_length=60, verbose_name='category1')),
                ('category1_a', models.CharField(max_length=60, verbose_name='category1_a')),
                ('category2', models.CharField(max_length=60, verbose_name='category2')),
                ('category2_a', models.CharField(max_length=60, verbose_name='category2_a')),
                ('category3', models.CharField(max_length=60, verbose_name='category3')),
                ('category3_a', models.CharField(max_length=60, verbose_name='category3_a')),
            ],
        ),
    ]
