# Generated by Django 4.2.2 on 2023-06-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_single_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='More_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name1', models.CharField(max_length=60, verbose_name='Button Name 1')),
                ('button_name2', models.CharField(max_length=60, verbose_name='Button Name 2')),
                ('text1', models.TextField(verbose_name='Text1')),
                ('text2', models.TextField(verbose_name='Text2')),
                ('text3', models.TextField(verbose_name='Text3')),
                ('text4', models.TextField(verbose_name='Text4')),
            ],
        ),
    ]
