# Generated by Django 4.2.2 on 2023-06-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_contact_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=60, verbose_name='name1')),
                ('name2', models.CharField(max_length=60, verbose_name='name2')),
                ('text', models.TextField(verbose_name='Text')),
                ('addres', models.CharField(max_length=60, verbose_name='adress')),
                ('phone', models.CharField(max_length=60, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
    ]
